POST http://localhost:3001/streamers
Content-Type: application/json

{
    "name": 2114,
    "description": "Streamer4's content focuses on travelling",
    "platform": "Twitch",
    "image": "https://static-cdn.jtvnw.net/jtv_user_pictures/asmongold-profile_image-f7ddcbd0332f5d28-300x300.png",
    "likes": 100
}